### ISSUE TITLE
Internal Server error response for POST /sensors/:id and GET /sensors/:id/data methods in sensorResource

### ISSUE THREAD

**Issue by priyapappachan** [scorelab/OpenIoE#4]
I used the following command for retrieving the data using REST endpoint
curl -X GET --header 'Accept: application/json' --header 'Authorization: Bearer <access_token>' 'http://127.0.0.1:8080/api/sensors/1/data'

I got the following response {
  "message": "error.internalServerError",
  "description": "Internal server error",
  "fieldErrors": null
}

The same error occurs for POST http://127.0.0.1:8080/api//sensors/:id. The sensor with id 1 is present.

**Comment by tharidu** [comment]
I guess it failed to create the correspending Cassandra table in 'ioe' keyspace. Can you check through web interface whether the created sensor is shown?

**Comment by priyapappachan** [comment]
Yes, the created sensor with id 1 is shown in the web interface under sensors tab.

**Comment by tharidu** [comment]
It's better if you can confirm in the keyspace in Cassandra has been created successfully using a client (ex DataStax client). Can you try to create another sensor with Store type field as NORMAL ?

In the new sensor UI, ideally `com.scorelab.ioe.nosql.StoreTypes` enum type should be mapped to Store type field as a combo box. You can do it as a task if you like to get to know the codebase.

**Comment by priyapappachan** [comment]
The problem was with the StoreType field value. The table data_x is getting created when a new sensor is created. I am able to perform POST /sensors/:id and GET /sensors/:id/data methods in sensorResource now. But there are no other tables created in keyspace for device and sensor data entries done using the interface.

**Comment by tharidu** [comment]
Cassandra data store only handles sensor data because of its scalability properties. Details about sensor and device information are stored in MySQL DB in the docker setup.
