### ISSUE TITLE
Npm issue

### ISSUE THREAD

**Issue by AshishA26** [scorelab/OpenIoE#54]
When I cloned the repository, I decided install the npm. I did it, but when I went to test the npm, it didn't work-there were many errors.
![capture](https://user-images.githubusercontent.com/44419439/49559790-f663da00-f8dd-11e8-81e1-963df7fc69b4.PNG)
The npm tests failed.

**Comment by psnmissaka** [comment]
@AshishA26  you are in the wrong directory to run the npm commands. Therefore this is not an issue.
